import React from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import GameComponent from '../../../components/gameComponent'
import SideScroller from '../../../components/sidescroller'
import { sampleGames } from '../../../utils/sampleData'

const Page = styled.div`
	background: linear-gradient(90deg, ${({theme}) => theme.primary} 21px, transparent 1%) center, linear-gradient(${({theme}) => theme.primary} 20px, transparent 1%) center, ${({theme}) => theme.secondary};
	background-size: 22px 22px;
	min-height: calc(100vh - 30px);
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding-top: 5rem;
	padding-bottom: 3rem;
`

const GameContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 2rem;
`

const OptionContainer = styled.div`
    margin: 1rem;
    display: flex;
    flex-direction: column;
    justify-content: center;
`

const GamePage = (props) => {

	return (
		<Page>
			<Head>
				<title>Game</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<GameContainer>
				<GameComponent 
					gameTitle={props.title}
					gameSrc={props.id}
				/>
				<OptionContainer>

					<SideScroller 
						items={sampleGames} 
						title='Recommended Games' 
					/>
				
				</OptionContainer>
			</GameContainer>

		</Page>
	)
}

export const getStaticPaths = async () => {
	return {
	  paths: [],
	  fallback: true
	}
}

export const getStaticProps = async (context) => {
	const props = context.params

	return {
		props: props
	}
}


export default GamePage