import React from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import GameComponent from '../../../components/gameComponent'


const Page = styled.div`
	background-color: #1a2c38;
	height: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding-top: 5rem;
	padding-bottom: 3rem;
`

export default function GamePage() {

	return (
		<Page>
			<Head>
				<title>Game </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<GameComponent 
				GameTitle='Sweet Bonanza' 
				GameProvider='Pragmatic Play' 
				gameSrc='https://www.analyticsinsight.net/wp-content/uploads/2022/11/Picture1-12.jpg'
			/>

		</Page>
	)
}
