import Head from 'next/head'
import { useRouter } from 'next/router'
import styled from 'styled-components'
import Tabs from '../../components/tabs'
import { DataGrid } from '@mui/x-data-grid'
import {
	Chart as ChartJS,
	CategoryScale,
	LinearScale,
	PointElement,
	LineElement,
	Title,
	Tooltip,
	Legend,
} from 'chart.js'
import { Line } from 'react-chartjs-2'
import db from '../../services/db'

const Page = styled.div`
	margin-bottom: 40px;
	height: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
`

const AdminHeader = styled.section`
  width: 100%;
  height: 400px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  background: radial-gradient(1.5em 6.28571em at 1.95em, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.25) 50%, rgba(255, 255, 255, 0.25) 55%, rgba(255, 255, 255, 0) 55%) 0 0, radial-gradient(1.5em 6.28571em at -0.45em, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.25) 50%, rgba(255, 255, 255, 0.25) 55%, rgba(255, 255, 255, 0) 55%) 1.5em 5.5em, radial-gradient(2.3em 4.57143em at 2.99em, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.3) 50%, rgba(255, 255, 255, 0.3) 55%, rgba(255, 255, 255, 0) 55%) 0 0, radial-gradient(2.3em 4.57143em at -0.69em, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.3) 50%, rgba(255, 255, 255, 0.3) 55%, rgba(255, 255, 255, 0) 55%) 2.3em 4em, radial-gradient(3.5em 6.28571em at 4.55em, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.25) 50%, rgba(255, 255, 255, 0.25) 55%, rgba(255, 255, 255, 0) 55%) 0 0, radial-gradient(3.5em 6.28571em at -1.05em, rgba(255, 255, 255, 0) 50%, rgba(255, 255, 255, 0.25) 50%, rgba(255, 255, 255, 0.25) 55%, rgba(255, 255, 255, 0) 55%) 3.5em 5.5em, radial-gradient(#00a8ff,#00fdff);
  background-color: mediumspringgreen;
  background-size: 1.5em 11em, 1.5em 11em, 2.3em 8em, 2.3em 8em, 3.5em 11em, 3.5em 11em, 100% 100%;
  background-repeat: repeat;
  box-shadow: 0 -6px 15px 7.5px rgba(0,0,0,0.5);
`
const TabContainer = styled.div`
  transform: translateY(-20%);
  width: 80vw;
  min-height: 60vh;
`

const ManageTeam = styled.div`
	height: 60vh;
	background-color: white;
`

const GraphContainer = styled.div`
	background-color: orange;
	height: 40vh;
	background-color: white;
`

const ContentManagement = styled.div`
	background-color: white;
	height: 60vh;
`

const Statistics = styled.div`
	background-color: white;
	min-height: 60vh;
`

const PageTitle = styled.h1`
	font-size: 70px;
	text-shadow: -1px 1px 0 #f00, 1px 1px 0 #F00, 1px -1px 0 #F00, -1px -1px 0 #F00;
	color: #FFBF00;
`

const AdminPage = (props) => {

	const router = useRouter()
	const { data } = props
	const columns = [
		{ field: 'uid', headerName: 'UID', width: 100},
		{ field: 'email', headerName: 'Email', width: 200 },
		{ field: 'name', headerName: 'Name', width: 100},
	]

	ChartJS.register(
		CategoryScale,
		LinearScale,
		PointElement,
		LineElement,
		Title,
		Tooltip,
		Legend
	)
	
	const options = {
		responsive: true,
		plugins: {
			legend: {
				position: 'top',
			},
			title: {
				display: true,
				text: 'Chart.js Line Chart',
			},
		},
	}
	
	const labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July']
	
	const data1 = {
		labels,
		datasets: [
			{
				label: 'Monthly Registered Users',
				data: labels.map(() => 50),
				borderColor: 'rgb(255, 99, 132)',
				backgroundColor: 'rgba(255, 99, 132, 0.5)',
			}
		],
	}
  
	const tabs = [
		{
			name: 'Manage Team',
			content: <ManageTeam >
				<DataGrid 
					rows={data}
					columns={columns}
					pageSize={10}
					rowsPerPageOptions={[5]}
        			checkboxSelection
				/>
			</ManageTeam>
		},
		{
			name: 'Statistics',
			content: <Statistics>
				<table className='charts-css line'>
					<caption>Total Users</caption>
					<thead>
						<tr>
							<th scope='col'>Count</th>
							<th scope='col'>Day</th>
						</tr>
					</thead>
					<tbody>
						{data.map(
							(entry, index) => {
								return <tr key={entry.id}>
									<th>{index}</th>
									<th>{entry.email}</th>
								</tr>
							}
						)}
					</tbody>
				</table>
				<GraphContainer>
					<Line data={data1} options={options} />
				</GraphContainer>
			</Statistics>
		}
	]

	if (router.isFallback) {
		return (
		  <div>loading</div>
		)
	} else {
		return (
			<Page>
				<Head>
					<title>Admin </title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<AdminHeader>
					<PageTitle>Admin Dashboard</PageTitle>
				</AdminHeader>

				<TabContainer>
					<Tabs tabs={tabs} path={router.pathname} />
				</TabContainer>
      
			</Page>
		)
	}
}
  
export const getStaticProps = async () => {
	const res = await db.collection('users').orderBy('created', 'desc').get()
	const entriesData = res.docs.map(entry => ({
		id: entry.id,
		...entry.data()
	}))

	return {
		props: { data: entriesData },
		revalidate: 10
	}
}

export default AdminPage