import Head from 'next/head'
import { useRouter } from 'next/router'
import styled from 'styled-components'
import Tabs from '../../components/tabs'

const Page = styled.div`
	margin-bottom: 40px;
	height: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
`

const AdminHeader = styled.section`
  width: 100%;
  height: 400px;
  background-color: blue;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
`
const TabContainer = styled.div`
  transform: translateY(-5%);
`

const ManageTeam = styled.div`
  background-color: Lime;
  height: 100%;
`

const WebsiteSettings = styled.div`
  background-color: orange;
  height: 100%;
`

const ContentManagement = styled.div`
  background-color: magenta;
  height: 100%;
`

const ContactAdmin = styled.div`
  background-color: yellow;
  height: 100%;
`

export default function AdminPage() {

	const router = useRouter()
  
	const tabs = [
		{
			name: 'Manage Team',
			content: <ManageTeam/>
		},
		{
			name: 'Website Settings',
			content: <WebsiteSettings />
		},
		{
			name: 'Content Management',
			content: <ContentManagement />
		},
		{
			name: 'Contact Admin',
			content: <ContactAdmin />
		}
	]

	return (
		<Page>
			<Head>
				<title>Admin </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<AdminHeader>
				<h1>Admin Dashboard</h1>
			</AdminHeader>

			<TabContainer>
				<Tabs tabs={tabs} path={router.pathname} />
			</TabContainer>
      
		</Page>
	)
}