import Head from 'next/head'
import styled from 'styled-components'
import { Fragment } from 'react'
import Carouse1 from '../../components/carousel'
import SideScroller from '../../components/sidescroller'
import { sampleGames } from '../../utils/sampleData'

const Page = styled.div`
	background: linear-gradient(90deg, ${({theme}) => theme.primary} 21px, transparent 1%) center, linear-gradient(${({theme}) => theme.primary} 20px, transparent 1%) center, ${({theme}) => theme.secondary};
	background-size: 22px 22px;
	min-height: calc(100vh - 30px);
	width: 100%;
	padding: 60px;
	display: flex;
	flex-direction: column;
	align-items: center;
`

const Title = styled.h1`
    font-weight: 900;
	text-align: center;
    padding-top: 20px;
    font-size: 30px;
    text-transform: uppercase;
	text-shadow: -1px 1px 0 #FFBF00, 1px 1px 0 #FFBF00, 1px -1px 0 #FFBF00, -1px -1px 0 #FFBF00;
`

const Showcase = styled(Carouse1)``

const showcaseGames = [
	sampleGames[0],
	sampleGames[1]
]

export default function Casino() {

	return (
		<Fragment>
			<Page>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<Title>Featured Games</Title>
				<Showcase carouselItems={showcaseGames} styles={{
					width: '600px'
				}}/>


				<SideScroller items={sampleGames} title='New Releases' />
				<SideScroller items={sampleGames} title='Card Games' />
				<SideScroller items={sampleGames} title='Casual Games' />
				<SideScroller items={sampleGames} title='Craps' />
				<SideScroller items={sampleGames} title='Lottery' />
				<SideScroller items={sampleGames} title='Poker' />
				<SideScroller items={sampleGames} title='Slots' />
				<SideScroller items={sampleGames} title='Video Poker' />

			</Page>
		</Fragment>
	)
}
