import Head from 'next/head'
import styled from 'styled-components'
import { Fragment } from 'react'
import Carouse1 from '../../components/carousel'
import SideScroller from '../../components/sidescroller'
import { sampleGames } from '../../utils/sampleData'

const Page = styled.div`
  min-height: calc(100vh - 30px);
  width: 100%;
  padding: 60px;
  display: flex;
  flex-direction: column;
  align-items: center;
`

const ShowcaseItem = styled.div`
  height: 300px;
  width: 100%;
  display: flex;
  align-items: center;
  padding: 20px;
  margin: 20px
`

const GamePicture = styled.div`
  height: 250px;
  width: 50%;
  background-color: yellow;
  margin: 20px;
  transform: translateX(15%);
`

const GameDescription = styled.div`
  height: 270px;
  transform: translateX(-15%);
  width: 50%;
  background-color: blue;
  border-radius: 15px;
  z-index: 1;
  padding: 20px;
  margin: 20px;
`

const Showcase = styled(Carouse1)``

const showcaseGames = [
	<ShowcaseItem key={1}>
		<GamePicture></GamePicture>
		<GameDescription>Lorem Ipsum</GameDescription>
	</ShowcaseItem>, 
	<ShowcaseItem key={2}>
		<GamePicture></GamePicture>
		<GameDescription style={{backgroundColor: 'green'}}>Lorem Ipsum</GameDescription>
	</ShowcaseItem>, 

]

export default function Casino() {

	return (
		<Fragment>
			<Page>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<h1>Casino Page</h1>
				<Showcase carouselItems={showcaseGames} title={'Showcase Game'} styles={{
					width: '100%', minWidth: '600px'
				}}/>


				<SideScroller items={sampleGames} title='Casino' />
				<SideScroller items={sampleGames} title='Slots' />
				<SideScroller items={sampleGames} title='Cards' />

			</Page>
		</Fragment>
	)
}
