import Head from 'next/head'
import { useRouter } from 'next/router'
import db from '../../services/db'
import styled from 'styled-components'
import Tabs from '../../components/tabs'
import ProfileSection from '../../components/profileSection'
import WalletSection from '../../components/walletSection'

const Page = styled.div`
	margin-bottom: 40px;
	height: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
`

const ProfileHeader = styled.section`
	width: 100%;
	height: 400px;
	display: flex;
	align-items: center;
	justify-content: center;
	color: white;
	box-shadow: 0 -6px 15px 7.5px rgba(0,0,0,0.5);
	background: linear-gradient(90deg, ${ ({theme}) => theme.accent } 18px, transparent 1%) center, linear-gradient(${ ({theme}) => theme.accent } 18px, transparent 1%) center, white;
	background-size: 22px 22px;
`

const ProfilePicture = styled.div`
	height: 250px;
	width: 250px;
	background-color: Lime;
	background-image: ${ props => props.profilePhoto ? `url("${props.profilePhoto}")` : 'none'};
	background-position: center;
	border-radius: 250px;
	text-align: center;
	display: flex;
	flex-direction: column;
	justify-content: center;
	font-size: 100px;
	color: red;
`

const TabContainer = styled.div`
	max-width: 750px;
	transform: translateY(-50px);
`


const Settings = styled.div`
	background-color: yellow;
	height: 100%;
`

export const tabNames =[
	'Profile',
	'Wallet',
	'Settings'
]

// user: database entry for the signed in user
// auth: auth instance
const Profile = ({user, auth}) => {
	const router = useRouter()
	// Get 'user' from the userDocument
  
	const tabs = [
		{
			name: 'Profile',
			content: <ProfileSection auth={auth} user={user} />
		},
		{
			name: 'Wallet',
			content: <WalletSection />
		},
		{
			name: 'Settings',
			content: <Settings />
		}
	]

	if (router.isFallback) {
		return (
		  <div>loading</div>
		)
	  } else {
		if (user) {
			return (
				<Page>
					<Head>
						<title>Profile </title>
						<meta name="description" content="Generated by create next app" />
						<meta name="viewport" content="width=device-width, initial-scale=1" />
						<link rel="icon" href="/favicon.ico" />
					</Head>

					<ProfileHeader>
						<ProfilePicture profilePhoto={user.profilePhoto}>
							{user.profilePhoto ? null : user.email[0].toUpperCase()}
						</ProfilePicture>
					</ProfileHeader>

					<TabContainer>
						<Tabs tabs={tabs} path={router.pathname} />
					</TabContainer>
			
				</Page>
			)
		}
		else {
			<div>How did you even get here lmao</div>
		}
	}
}

export const getStaticPaths = async () => {
	const users = await db.collection('users').get()
	const paths = users.docs.map(user => ({
	  params: {
			userId: user.data().uid
	  }
	}))
	return {
	  paths,
	  fallback: true
	}
}
  
export const getStaticProps = async (context) => {
	const { userId } = context.params
	const res = await db.collection('users').where('uid', '==', userId).get()
	const user = res.docs.map(user => user.data())
	if (user.length) {
	  return {
			props: {
		  		user: user[0]
			}
	  }
	} else {
	  return {
			props: {}
	  }
	}
}
  
export default Profile