import Head from 'next/head'
import { useRouter } from 'next/router'
import styled from 'styled-components'
import Tabs from '../../components/tabs'

const Page = styled.div`
  margin-bottom: 40px;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`

const ProfileHeader = styled.section`
  width: 100%;
  height: 400px;
  background-color: blue;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
`

const ProfilePicture = styled.div`
  height: 250px;
  width: 250px;
  background-color: Lime;
  border-radius: 250px;
  text-align: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
  font-size: 100px;
  color: red;
`

const TabContainer = styled.div`
  transform: translateY(-5%);
`

const Wallet = styled.div`
  background-color: Lime;
  height: 100%;
`

const Statistics = styled.div`
  background-color: orange;
  height: 100%;
`

const Transactions = styled.div`
  background-color: magenta;
  height: 100%;
`

const Settings = styled.div`
  background-color: yellow;
  height: 100%;
`

export default function Profile() {

	const tabs = [
		{
			name: 'Wallet',
			content: <Wallet />
		},
		{
			name: 'Statistics',
			content: <Statistics />
		},
		{
			name: 'Transactions',
			content: <Transactions />
		},
		{
			name: 'Settings',
			content: <Settings />
		}
	]

	const router = useRouter()
  
	return (
		<Page>
			<Head>
				<title>Profile </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<ProfileHeader>
				<ProfilePicture>
          C
				</ProfilePicture>
			</ProfileHeader>

			<TabContainer>
				<Tabs tabs={tabs} path={router.pathname} />
			</TabContainer>
      
		</Page>
	)
}
