import Head from 'next/head'
import styled from 'styled-components'
import SideScroller from '../components/sidescroller'
import { sampleGames } from '../utils/sampleData'

const Page = styled.div`
	margin: 0;
	padding: 0;
`

const Hero = styled.section`
  width: 100%;
  height: 600px;
  background-color: blue;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
`

const Body = styled.section`
  width: 100%;
  padding: 20px;
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
`

export default function Home() {

	return (
		<Page>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Hero>
        		Hero Banner
			</Hero>

			<Body>
				<SideScroller items={sampleGames} title='Casino' />
				<SideScroller items={sampleGames} title='Slots' />
				<SideScroller items={sampleGames} title='Cards' />
			</Body>
		</Page>
	)
}
