import Head from 'next/head'
import styled from "styled-components"
import SideScroller from '../components/sidescroller'

const Page = styled.div`
  padding: 30px;
`

const Hero = styled.section`
  width: 100%;
  height: 600px;
  background-color: blue;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
`

const Body = styled.section`
  width: 100%;
  padding: 20px;
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
`

export default function Home() {

  const sampleGames = [
    {id: 1, content: <p>Hello</p>}, 
    {id: 2, content: <p>World</p>}, 
    {id: 3, content: <p>!</p>},
    {id: 4, content: <p>Hello</p>}, 
    {id: 24, content: <p>World</p>}, 
    {id: 33, content: <p>!</p>},
    {id: 15, content: <p>Hello</p>}, 
    {id: 25, content: <p>World</p>}, 
    {id: 332, content: <p>!</p>},
    {id: 12, content: <p>Hello</p>}, 
    {id: 27, content: <p>World</p>}, 
    {id: 38, content: <p>!</p>},
  ]

  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero>
        Hero Banner
      </Hero>

      <Body>
        <SideScroller items={sampleGames} title='Casino' />
        <SideScroller items={sampleGames} title='Slots' />
        <SideScroller items={sampleGames} title='Cards' />
      </Body>
    </Page>
  )
}
