import React from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import SideScroller from '../../../components/sidescroller'
import { sampleGames } from '../../../utils/sampleData'


const Page = styled.div`
	background-color: #1a2c38;
	min-height: calc(100vh - 30px);
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding-top: 5rem;
	padding-bottom: 3rem;
`


export default function CategoryPage(){

	return(
		<Page>
			<Head>
				<title>Game </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>


			<SideScroller 
				items={sampleGames} 
				title='Recommended Games' 
			/>
				
				

		</Page>
	)
}