import React, { useEffect, useState } from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import { sampleGames } from '../../../utils/sampleData'
import { useRouter } from 'next/router'
import GameCard from '../../../components/gameCard'


const Page = styled.div`
	background: linear-gradient(90deg, ${({theme}) => theme.primary} 21px, transparent 1%) center, linear-gradient(${({theme}) => theme.primary} 20px, transparent 1%) center, ${({theme}) => theme.secondary};
	background-size: 22px 22px;
	min-height: calc(100vh - 30px);
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding-top: 5rem;
	padding-bottom: 3rem;
`

const GamesBox = styled.div`
	min-height: calc(100vh - 40px);
	max-width: 1000px;
	display: flex;
	flex-flow: column wrap;
	margin: 40px;
	border-radius: 15px;
	background-color: ${ ({theme}) => theme.secondary };
	padding: 20px;
`

const GamesViewer = styled.div`
	min-height: calc(100vh - 40px);
	max-width: 960px;
	display: flex;
	flex-flow: row wrap;
	border-radius: 15px;
	background: rgba(0,0,0,0.2);
	position: relative;
`

const PageTitle = styled.h1`
	font-size: 45px;
	text-shadow: -1px 1px 0 #f00, 1px 1px 0 #F00, 1px -1px 0 #F00, -1px -1px 0 #F00;
	color: #FFBF00;
	width: 100%;
	text-align: center;
	padding-bottom: 20px;
`

const Overlay = styled.div`
	border-radius: 15px;
	position: absolute;
	background: linear-gradient(90deg, rgba(0,0,0,0.4) 0%, rgba(9,9,121,0) 5%, rgba(9,9,121,0) 95%, rgba(0,0,0,0.4) 100%);
	top:0;
	left:0;
	width: 100%;
	height:100%;
	color:black;
	text-align: center;
	z-index: 10;
	pointer-events: none;	
`

export default function CategoryPage() {

	const router = useRouter()
	const casinoCategory = router.query.casinoCategory
	const [title, setTitle] = useState()

	const formatTitle = (str) => {
		if(str != undefined) {
			str = str.replace(/_/g, ' ')
			var reg = /\b([a-zÁ-ú]{3,})/g
 			str = str.replace(reg, (w) => w.charAt(0).toUpperCase() + w.slice(1))
			return str
		}
	}

	// When category is known update and format the title
	useEffect(() => {
		setTitle(casinoCategory)
	}, [casinoCategory])

	return(
		<Page>
			<Head>
				<title>Game </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<GamesBox>
				<PageTitle>
					{formatTitle(title)}
				</PageTitle>

				<GamesViewer >
					<Overlay />
					{
						sampleGames.map(
							(game, index) =>
							{
								return <GameCard item={game} key={index} shape='wide' />
							}
						)
					}
				</GamesViewer>
			</GamesBox>
		</Page>
	)
}